# Generated by Django 3.2.11 on 2022-02-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Core Page',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('on_footer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('position', models.IntegerField()),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_type', to='core.componenttype', to_field='component_name')),
                ('core_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_page', to='core.corepage', to_field='title')),
            ],
        ),
        migrations.AddField(
            model_name='corepage',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.menu'),
        ),
    ]
