# Generated by Django 3.2.11 on 2022-02-28 16:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
