# Generated by Django 3.2.11 on 2022-02-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Latest News',
            },
        ),
        migrations.CreateModel(
            name='KnowAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Know About Us',
            },
        ),
        migrations.CreateModel(
            name='Glance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Glance',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='ComponentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_data', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Component Data',
            },
        ),
        migrations.CreateModel(
            name='CardMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Card Menu',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('position', models.IntegerField()),
                ('on_landing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_section', to='core.section')),
            ],
            options={
                'verbose_name_plural': 'Announcement',
            },
        ),
    ]
