# Generated by Django 3.2.11 on 2022-02-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('sub_image', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('footer_icon', models.ImageField(blank=True, upload_to='')),
                ('footer_sub_image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'Social Link',
            },
        ),
    ]
